### ISSUE TITLE
[Feature Request]: Allow colors in punishment-expired-display

### ISSUE THREAD

**Issue by fabianmakila** [A248/LibertyBans#228]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Some servers might want to color code the `Expired` and `Not expired` texts seen in the `/history` command to make it easier to differentiate between the two by a quick glance.

My first intuition was to do this which doesn't work currently.
```yml
  punishment-expired-display:
     # How do you describe an expired punishment?
    expired: '&cExpired'
     # How do you describe a punishment which is not expired?
    not-expired: '&aNot expired'
```

I'm proposing the addition of color code support for the two fields above, which would allow the use of colors without adding any additional fields to the configuration.
