### ISSUE TITLE
[Feature Request]: Custom layout for reason

### ISSUE THREAD

**Issue by kayeradev** [A248/LibertyBans#307]
### I have confirmed that ...

- [x] There is no duplicate feature request.

### Description

For example, if I ban a player for “media-cheating”, there will be a custom layout specifically for this reason. At the bottom, for example, instead of the "https://kayera.software/", it will say “Contact us from media@kayera.software”.

Something like this:

```
reason-layouts:
  media-cheating:
    layout:
      - '&7&lBanned&f'
      - '&cDuration: &e%TIME_REMAINING%&f'
      - ''
      - '&c&lReason&f'
      - '&7Cheating&f'
      - ''
      - '&3&lAppeal Your Punishment&f'
      - '&cContact us on Discord&f'
      - '&cDiscord: &7discord'
  cheating:
    layout:
      - '&7&lBanned&f'
      - '&cDuration: &e%TIME_REMAINING%&f'
      - ''
      - '&c&lReason&f'
      - '&7Cheating&f'
      - ''
      - '&3&lAppeal Your Punishment&f'
      - '&cWebsite: &7website&f'
      - '&cDiscord: &7discord'
```
